#define FUNCNAME_quitfm 0
#define FUNCNAME_accessKey 1
#define FUNCNAME_adBmark 2
#define FUNCNAME_setAlarm 3
#define FUNCNAME_backBf 4
#define FUNCNAME_goLineF 5
#define FUNCNAME_ldBmark 6
#define FUNCNAME_ctrCsrH 7
#define FUNCNAME_ctrCsrV 8
#define FUNCNAME_docCSet 9
#define FUNCNAME_closeT 10
#define FUNCNAME_closeTMs 11
#define FUNCNAME_execCmd 12
#define FUNCNAME_cooLst 13
#define FUNCNAME_defCSet 14
#define FUNCNAME_defKey 15
#define FUNCNAME_deletePrevBuf 16
#define FUNCNAME_dictwordat 17
#define FUNCNAME_dictword 18
#define FUNCNAME_dispI 19
#define FUNCNAME_ldown1 20
#define FUNCNAME_ldDL 21
#define FUNCNAME_svSrc 22
#define FUNCNAME_editBf 23
#define FUNCNAME_editScr 24
#define FUNCNAME_goLineL 25
#define FUNCNAME_escbmap 26
#define FUNCNAME_escmap 27
#define FUNCNAME_execsh 28
#define FUNCNAME_extbrz 30
#define FUNCNAME_linkbrz 31
#define FUNCNAME_rFrame 32
#define FUNCNAME_goURL 33
#define FUNCNAME_goLine 34
#define FUNCNAME_followA 35
#define FUNCNAME_gorURL 36
#define FUNCNAME_ldhelp 37
#define FUNCNAME_ldHist 38
#define FUNCNAME_pginfo 39
#define FUNCNAME_susp 40
#define FUNCNAME_isrchbak 41
#define FUNCNAME_isrchfor 42
#define FUNCNAME_col1L 43
#define FUNCNAME_linbeg 44
#define FUNCNAME_linend 45
#define FUNCNAME_curlno 46
#define FUNCNAME_topA 47
#define FUNCNAME_lastA 48
#define FUNCNAME_linkMn 49
#define FUNCNAME_linkLst 50
#define FUNCNAME_listMn 51
#define FUNCNAME_ldfile 52
#define FUNCNAME_mainMn 53
#define FUNCNAME__mark 54
#define FUNCNAME_chkNMID 55
#define FUNCNAME_chkURL 56
#define FUNCNAME_chkWORD 57
#define FUNCNAME_menuMs 59
#define FUNCNAME_mouse 60
#define FUNCNAME_msToggle 61
#define FUNCNAME_movD1 62
#define FUNCNAME_movD 63
#define FUNCNAME_movL1 64
#define FUNCNAME_movL 65
#define FUNCNAME_movlistMn 66
#define FUNCNAME_movMs 67
#define FUNCNAME_movR1 68
#define FUNCNAME_movR 69
#define FUNCNAME_movU1 70
#define FUNCNAME_movU 71
#define FUNCNAME_msgs 72
#define FUNCNAME_multimap 73
#define FUNCNAME_newT 74
#define FUNCNAME_nextD 75
#define FUNCNAME_nextL 76
#define FUNCNAME_nextLU 77
#define FUNCNAME_nextA 78
#define FUNCNAME_nextMk 79
#define FUNCNAME_nextBf 80
#define FUNCNAME_pgFore 81
#define FUNCNAME_nextRD 82
#define FUNCNAME_nextR 83
#define FUNCNAME_nextT 84
#define FUNCNAME_nextU 85
#define FUNCNAME_nextVA 86
#define FUNCNAME_movRW 87
#define FUNCNAME_nulcmd 88
#define FUNCNAME_ldOpt 91
#define FUNCNAME_pcmap 92
#define FUNCNAME_curURL 93
#define FUNCNAME_peekIMG 94
#define FUNCNAME_peekURL 95
#define FUNCNAME_pipeBuf 96
#define FUNCNAME_pipesh 97
#define FUNCNAME_prevA 98
#define FUNCNAME_prevMk 99
#define FUNCNAME_pgBack 100
#define FUNCNAME_prevBf 101
#define FUNCNAME_prevT 102
#define FUNCNAME_prevVA 103
#define FUNCNAME_movLW 104
#define FUNCNAME_svBuf 105
#define FUNCNAME_qquitfm 106
#define FUNCNAME_readsh 107
#define FUNCNAME_redoPos 108
#define FUNCNAME_rdrwSc 109
#define FUNCNAME_reMark 110
#define FUNCNAME_reinit 111
#define FUNCNAME_reload 112
#define FUNCNAME_reshape 113
#define FUNCNAME_col1R 114
#define FUNCNAME_svI 115
#define FUNCNAME_svA 116
#define FUNCNAME_srchbak 119
#define FUNCNAME_srchfor 120
#define FUNCNAME_srchnxt 121
#define FUNCNAME_srchprv 122
#define FUNCNAME_selMn 124
#define FUNCNAME_selBuf 125
#define FUNCNAME_setEnv 126
#define FUNCNAME_setOpt 127
#define FUNCNAME_shiftl 129
#define FUNCNAME_shiftr 130
#define FUNCNAME_vwSrc 131
#define FUNCNAME_stopI 132
#define FUNCNAME_submitForm 133
#define FUNCNAME_tabrURL 135
#define FUNCNAME_tabURL 136
#define FUNCNAME_tabL 137
#define FUNCNAME_tabA 138
#define FUNCNAME_tabMn 139
#define FUNCNAME_tabMs 140
#define FUNCNAME_tabR 141
#define FUNCNAME_undoPos 142
#define FUNCNAME_lup1 143
#define FUNCNAME_dispVer 144
#define FUNCNAME_followI 146
#define FUNCNAME_wrapToggle 149
